name: 'Issue Label Notifier'
description: 'Notify individuals or teams based on issue labels.'
inputs:
  token:
    description: 'The GitHub authentication token.'
    default: ${{ github.token }}
    required: false

runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: 'bell'
  color: 'gray-dark'
