name: CI
on:
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        multiply: [Debug, Release, Windows, Linux]
    steps:
    - uses: actions/heroku@master
    - run: exit 1

