name: CI
on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - uses: ./.
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        add-labels: "needs-triage, bug"
        ignore-if-assigned: true
