name: CI
on:
  workflow_dispatch:

jobs:
  one:
    runs-on: [ubuntu-latest, windows-latest]
    strategy:
      matrix:
        multiply: [Debug, Release, Windows, Linux]
    steps:
    - uses: actions/checkout@master
    - run: exit 1
    continue-on-error: true
  two:
    runs-on: [ubuntu-latest, windows-latest]
    strategy:
      matrix:
        multiply: [Debug, Release, Windows, Linux]
    steps:
    - uses: actions/checkout@master
    - run: exit 1
    continue-on-error: true
