name: Label

on:
  issues: 
    types: [labeled]
    
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      - uses: ben-z/actions-comment-on-issue@1.0.2
        if: github.event.label == 'enhancement'
        with:
          message: "This is a test" 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

   
